### ISSUE TITLE
HentaiParser 有些 issue

### ISSUE THREAD

**Issue by DaidoujiChen** [Splendent/ehGalleryViewer#9]
Hello @Splendent,

經過一些回報跟測試, 我發現 HentaiParser 裡面有一些會造成 crash 的地方, 在 https://github.com/DaidoujiChen/Dai-Hentai/issues/11#issuecomment-68481512 這邊找到了兩個有問題的點, 然後有把他 fix, 我看一下你用的應該還是之前的, 所以跟你說一下, 可以直接去我那邊抓新的版本來用, O3O, 謝謝.

**Comment by Splendent** [comment]
感謝:x
